ipfs/js-ipfs-utils

package.json, src/files/normalise-input.js, test/files/normalise-input.spec.js
This PR updates the `normaliseInput` function to accept pull streams.
I've also made the following changes:
1. Update the docs for supported inputs
* `Buffer|ArrayBuffer|TypedArray` is aliased as `Bytes`
* `Blob|File` is aliased as `Bloby`
* Added info for what a input "means" i.e. causes single/multiple files to be added
1. Peek the first item of an (async) iterator properly
1. Move file object check below `input[Symbol.asyncIterator]` check because Node.js streams have a path property that will false positive the `isFileObject` check
1. Fix `toFileObject` to allow objects with no `content` property
1. Simplify `toBuffer` to remove checks that `Buffer.from` already does
=> feat: support pull streams

package.json, src/files/normalise-input.js, test/files/normalise-input.spec.js
This PR follows on from [this comment](https://github.com/ipfs/js-ipfs/pull/2379#discussion_r316549458) and allows an input normalisation function to be shared between ipfs and the http client.
All supported types are tested, at the moment they are (from the test output):
```
normalise-input
String
✓ String
✓ { path: '', content: String }
✓ Iterable<{ path: '', content: String }
✓ AsyncIterable<{ path: '', content: String }
✓ PullStream<{ path: '', content: String }
Buffer
✓ Buffer
✓ Iterable<Buffer>
✓ AsyncIterable<Buffer>
✓ PullStream<Buffer>
✓ { path: '', content: Buffer }
✓ { path: '', content: Iterable<Buffer> }
✓ { path: '', content: AsyncIterable<Buffer> }
✓ { path: '', content: PullStream<Buffer> }
✓ Iterable<{ path: '', content: Buffer }
✓ AsyncIterable<{ path: '', content: …
```
=> feat: add normalise input function

package.json, src/files/glob-source.js, test/files/glob-source.spec.js
The business of turning a path and pattern into an iterator of files is duplicated between `js-ipfs` and `js-ipfs-http-client` so moving it here to aid deduplication.
=> feat: add glob-source from js-ipfs so it can be shared with the http client

src/env.js
> This PR unblocks https://github.com/ipfs/js-ipfs/pull/2304/#discussion_r321227711 
Adds `isTest` check to tell if runtime is part of tests: 
```js
process.env.NODE_ENV === 'test'
```
It does it in a way that works in browser  without `process.env` polyfills
=> feat: env/isTest

package.json, src/files/normalise-input.js, test/files/normalise-input.spec.js
In order not to break our users, this PR adds support for normalising instances the [`readable-stream`](https://www.npmjs.com/package/readable-stream) module @v2 and @v3 as input to `ipfs.add`.
=> feat: support old school streams

src/files/format-mtime.js, test/files/format-mtime.spec.js
Currently formats dates as `Jan 1, 1970, 1:00:00 AM GMT+1` - we may wish to revisit this later but we can do so in a subsequent PR.
=> fix: format mtime as timespec

src/files/normalise-input.js, test/files/normalise-input.spec.js
N.b you can't read from a browser readable stream repeatedly as the first call to `stream.getReader` locks the reader to the first invocation so I had to change all the test data to be functions that return a new instance of the data.
=> feat: accept browser readable streams as input

package.json
16 has https://github.com/sindresorhus/ky/issues/209
15 is also the version currently used by js-ipfs and js-ipfs-http-client
=> fix: downgrade to ky 15

src/files/glob-source.js, test/files/glob-source.spec.js
See https://github.com/ipfs/js-ipfs-unixfs#create-an-unixfs-data-element  - it should be `Date | object | array`.
Ends up ignored https://github.com/ipfs/js-ipfs-unixfs/blob/master/src/index.js#L104-L106
=> fix: number is not a valid mtime value

.aegir.js, README.md, package.json, src/files/normalise-input.js, src/files/url-source.js, src/http.js, src/text-encoder.browser.js, src/text-encoder.js, test/files/format-mtime.spec.js, test/http.spec.js, test/utils/chai.js
Splits the code out of the monorepo as it's used in other places, so needs to be released independently.
=> feat: import code from monorepo

src/http.js, src/text-encoder.browser.js
Closes https://github.com/ipfs/js-ipfs-utils/issues/29
=> fix: avoid Identifier 'global' has already been declared

src/http.js
Workaround for https://github.com/node-fetch/node-fetch/issues/766
Fixes the intermittent build failures around `ipfs.dht.findPeer` introduced by https://github.com/ipfs/js-ipfs/pull/2965
=> fix: destroy request body when we are aborting it midway though reading

src/http.js
Sometimes `.writable` is false due to a race condition so use `hasOwnProperty` instead.
Also destroys the stream when we are done with the iterator reguardless.
=> fix: detect node stream with hasOwnProperty

src/http.js, test/http.spec.js
The conventions in the Fetch API is that you make a request, then do something with the response:
```javascript
const response = await fetch('...')
const data = await response.json()
```
It doesn't do things like:
```javascript
const data = await fetch.json('...') // what method would this use?
```
This PR brings our API more inline with Fetch so where we used to do:
```javascript
for await (const datum of http.ndjson('...')) { // what method does this use?
}
```
We now do the more idiomatic:
```javascript
const response = await http.post('...')
for await (const datum of response.ndjson()) {
}
```
It also removes the `.iterator` and `.stream` methods as they do not follow the Fetch pattern either though they can be added to the response object if they are useful.
=> fix: simplify http client

package.json, src/files/url-source.js, src/http.js, test/files/url-source.spec.js, test/http.spec.js
Restores the previous `.iterator` method but on the response object similar to `.ndjson`:
```javascript
const response = await http.get('http://...')
for await (const buf of response.iterator()) {
// buf is a Buffer
}
```
Also adds a test for urlSource because it turns out it uses `.iterator` but was untested.
=> feat: add iterator method to response

src/files/url-source.js
It looks like the function was written to allow this as a parameter, but it was never used. This should allow for use cases like specifying custom headers while using `urlSource`. The `node-fetch` module falls back on [default options](https://github.com/node-fetch/node-fetch#options) if none are specified, so we shouldn't need to check and send an empty object at this step.
=> feat: pass in Options Object to http Constructor

src/http.js, test/http.spec.js
Sometimes a request can resolve before the timeout callback fires, this can be because the system is under load and the event loop is blocked.
This change looks at the time taken by a request to resolve when deciding if it's timed out as well as setting a regular js timeout to catch inactive requests.
It also removes the `timeout` option passed to `node-fetch` as it implements it's own timeout feature which results in two types of timeout error that can occur - ours and `node-fetch`'s.
=> fix: make timeouts stricter

package.json, src/http.js, test/http.spec.js
Adds tests for the same.
Depends on:
=> fix: fix headers and abort signals

package.json, src/http.js, src/text-decoder.browser.js, src/text-decoder.js, src/text-encoder.browser.js, src/text-encoder.js, test/text-codec.spec.js
Context: @hugomrdias proposed to import `TextEncoder` from `text-encoder` which as it turns out exposes `TextDecoder` instead. 
https://github.com/ipfs/protons/pull/13#pullrequestreview-427374776
This change does following:
1. Adds text-decoder module to expose `TextDecoder`.
2. Changes text-encoder module to expose `TextEncoder`.
3. Adds a test that exercises both.
=> Text encoder decoder

src/supports.js, test/supports.spec.js
The use of WebRTC in IPFS is only as a data channel, we don't use getUserMedia and sometimes the user has restricted access to this API so add a 'supports' test that is just for data channels.
Fixes #50
=> feat: detect support for WebRTC data channels

package.json, src/http.js, src/http/error.js, src/http/fetch.browser.js, src/http/fetch.js, src/http/fetch.node.js, test/http.spec.js
As per #52 this adds `onUploadProgress` / `onDownloadProgress` optional handlers. Intention is to allow ipfs-webui to render file upload progress when new content is added.
Fixes #52
=> feat: http upload/download progress handlers

package.json, src/fetch.js
No need to use the fork any more as the original bug has been [fixed](https://github.com/arantes555/electron-fetch/pull/31).
The js-IPFS build passes with this change: https://github.com/ipfs/js-ipfs/pull/3414
=> chore: revert to upstream electron-fetch

package.json, src/http.js, test/http.spec.js, types/native-abort-controller/index.d.ts
To avoid extending built-in classes you now need to use named exports when importing `native-abort-controller`.
=> chore: update native-abort-controller

package.json, src/files/glob-source.js, test/files/glob-source.spec.js
Date is not fine grained enough - nanoseconds are ignored so expand
the supported types of time representation allowed.
=> fix: allow all supported unixfs time types

.aegir.js, package.json, src/http.js, src/http/error.js, src/http/fetch.node.js, src/types.d.ts, src/types.ts
Use our imaginary native-fetch types instead as they do not require
consuming modules to also depend on electron-fetch.
=> fix: do not use electron-fetch types

src/text-decoder.js, src/text-encoder.js, test/text-codec.spec.js
Datastores in the wild use these functions so remove web-encoding without breaking the public api.
=> chore: remove web-encoding in a backwards compatible way

package.json
Fixes this issue: https://github.com/ipfs/js-ipfs/issues/3557
Related PR in `js-ipfs`: https://github.com/ipfs/js-ipfs/pull/3630
=> fix: exclude glob-source.js in browser build

package.json, src/files/glob-source.js, test/files/glob-source.spec.js
The fs module has promises support so just use that instead.
=> chore: remove fs-extra

package.json
https://github.com/node-fetch/node-fetch/pull/1064 fixes a bug in node-fetch to make it handle situations where the stream closes prematurely but it's been merged into the v3 release tree which is still future tech with no release date.
https://github.com/node-fetch/node-fetch/pull/1172 backports that fix to v2 but although approved it's not been merged and released yet so here we use a temporary fork published with that PR merged in.
=> fix: use node-fetch fork with fix for stream closed prematurely bug

src/types.d.ts
Fixes two problems:
1. The import for `NodeReadableStream` was missing
2. We can't use `NodeReadableStream` as the type for `body` because it it not assignable to any type that makes up `BodyInit` so instead [modify](https://stackoverflow.com/questions/41285211/overriding-interface-property-type-defined-in-typescript-d-ts-file) the RequestInit type to omit the original `body` type and include the new one.
Fixes this error:
```
node_modules/ipfs-utils/dist/src/types.d.ts:11:18 - error TS2430: Interface 'FetchOptions' incorrectly extends interface 'RequestInit'.
Types of property 'body' are incompatible.
Type 'Readable | BodyInit | null | undefined' is not assignable to type 'BodyInit | null | undefined'.
Type 'Readable' is not assignable to type 'BodyInit | null | undefined'.
Type …
```
=> fix: request body type

.github/workflows/main.yml, package.json, src/http.js, test/http.spec.js
`AbortController` and `AbortSignal` are supported in browsers and node 14+ so the extra deps aren't necessary any more.
=> fix: remove abort controller deps

README.md, package.json
=> chore: add semantic release config

src/env.js
Access process as a property of `globalThis` instead of as a global
as parcel has stopped bundling the polyfill.
Fixes:
```
ipfs: @parcel/core: Failed to resolve 'process' from
ipfs: './node_modules/ipfs-utils/src/env.js'
ipfs:   /tmp/test-dependant-1646117523100/node_modules/ipfs-utils/src/env.js:10:57
ipfs:      9 | const IS_ELECTRON_RENDERER = IS_ELECTRON && IS_ENV_WITH_DOM
ipfs:   > 10 | peof process !== 'undefined' && typeof process.release !== 'undefined'
ipfs:   >    |      ^^^^^^^
ipfs:     11 | // @ts-ignore - we either ignore worker scope or dom scope
ipfs:     12 | const IS_WEBWORKER = typeof importScripts === 'function' && typeof self
ipfs: @parcel/resolver-default: Node builtin polyfill "process" is not installed, but
ipfs: auto install is disabled.
```
=> fix: detect process before use

src/files/glob-source.js
Motivation:
* Fix https://github.com/ipfs/js-ipfs/issues/4080
* tl;dr
* fix `import globSourceImport from 'ipfs-utils/src/files/glob-source.js'` from typescript
* fix importing ipfs-core from typescript
Context:
* https://github.com/microsoft/TypeScript/issues/23857
Strategy
* Use jsdoc `@return` instead of `@yields` because tsc doesn't understand that `@yields` implies a `@return` type
Test Case
* https://github.com/gobengo/ipfs-core-esm-test/pull/3
* I tested locally with `npm link` and this seemed to fix it
=> fix: swap @yields for @returns

src/files/glob-source.js, src/types.d.ts
Update import for `MtimeLike` type otherwise incorrect paths are generated during compilation.
=> fix: fix unixfs import

src/files/glob-source.js
Fixes:
```
node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:2:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.
2 export = _exports;
```
=> fix: only export one thing from glob source

.github/dependabot.yml, .github/workflows/js-test-and-release.yml, LICENSE, LICENSE-APACHE, LICENSE-MIT, README.md, package.json, src/http.js, src/http/fetch.node.js, test/http.spec.js
A recent change to the fetch spec means the `duplex` option has to be set to `half` when using a `ReadbleStream` as the request body.
=> fix: specify duplex option

package.json
https://github.com/node-fetch/node-fetch/pull/1172 finally got released so we can remove the fork now.
=> deps: update node-fetch to 2.6.8
